## Return Intervals 

- In this learning module we will quantify the magnitude and frequency of the precipitation 'forcing' to move from observation to prediction. This week introduces statistical frequency analysis and return intervals to evaluate the rarity of the events driving our process-based models.

### Learning Module 2

#### Background information

In the previous module, we performed hydrograph separation across three watersheds and we looked at the final output of complex system (the streamflow). By comparing patterns across the three watersheds, we looked at the response (the outcome) and worked backward to identify the processes influencing baseflow and quickflow. Your process-based explanations likely touched on:

  Storage: Soil depth and groundwater capacity.

  Surface Characteristics: Land cover and urbanization.

  Losses: Evapotranspiration and infiltration rates.

However, a watershed’s behavior is only half of the story. A high runoff ratio is interesting because it reflects watershed behavior, but it doesn't tell us how frequently the system produces extreme flows or floods. Now that you can separate baseflow from quickflow, you have the tools to link storm inputs to peak discharge. The next step is to evaluate precipitation using the same quantitative mindset. This shift marks our first step from qualitative process reasoning toward predictive modeling.

In other words, we’ve asked: "What did the watershed do with the water it received?" Now we'll ask: "How rare or extreme was the water it received in the first place?"

To answer this question, we'll explore return intervals (or recurrence intervals). Return intervals are a probabilistic model that summarize historical precipitation records to estimate the likelihood of extreme events. They do not predict when a storm will occur; instead, they describe the probability that a given magnitude will be exceeded in any year. In professional practice, we rarely design for "average" days, we design for the extremes.

In last week's analysis, we assumed that the forcing was the same for all 3 watersheds. Now let's imagine we are evaluating a single watershed and see a massive spike in a hydrograph. To interpret the event, we need to know:

Was this a relatively common storm impacting a low-storage watershed?

Or was it a once-in-one hundred-years storm hitting a watershed that usually buffers flow?

By calculating return intervals using Precipitation Duration, Frequency, and Intensity (IDF) curve, we begin to quantify the hydrologic risk.

##### Connecting to our R Workflow

Before we can build a process model that predicts future runoff, we must understand the statistical characteristics of rainfall like magnitude, timing, and variability. Just as we used R to automate the separation of baseflow, we will now use it to fit statistical distributions to historical rainfall and calculating exceedance probabilities.

Check out this lecture from colleague Joel Sholtes on precipitation frequency analysis. You can ignore his references to 'assignments' and end the lecture around the 26 minute mark.

<iframe width="560" height="315" src="https://www.youtube.com/embed/3_EnTJaFCKg?si=1BYvBzA1fDjZK4Zv" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>


Short lecture on Intensity-Duration-Frequency (IDF) curves

<iframe width="560" height="315" src="https://www.youtube.com/embed/JXSwKmfMZJo?si=nlHa4Th3ZCSzi2Ks" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

Reading on frequency analysis of flow (e.g., floods). You should notice that the frequency analysis is the same whether we apply it to Q (flow) or P (precipitation). So as long as you understand the fundamental principles you will be able to do frequency analysis on either Q or P. 

[USGS reading on flow frequency analysis](https://www.usgs.gov/centers/new-jersey-water-science-center/floods-recurrence-intervals-and-100-year-floods){target="_blank"}

If you would like a refresher, there are also probability lecture slides on Canvas titled "probability.pptx". 
 
### Repo link

The repo for this module can be found [here](https://github.com/tpcovino/02_return_intervals.git){target="_blank"}

