## Rational method and NRCS curve number (20 pts)

### Learning Module 3

#### Background information - Rational Method

In the previous module, we worked with our first probability-based model: return intervals. A model is simply an equation, or set of equations, that represents environmental processes and their interactions to estimate an outcome. Models act as maps of environmental systems: they are useful for understanding and prediction, but they are not exact representations of reality. As the statistician George Box famously noted, “All models are wrong, but some are useful.”

Return intervals are a model because they summarize past observations into a probabilistic description of extreme events. They do not predict when a storm will occur, nor do they describe the physical processes that generate rainfall. Instead, they provide a simplified, probability-based way of representing risk that can be used in hydrologic analysis and design.

In this module, we build on that foundation by introducing parameters. Parameters are numerical values within a model that summarize key characteristics or processes of a system and strongly influence model outputs. In hydrology, parameters often represent watershed properties such as land cover, soil type, or infiltration capacity.

The Rational Method and the Curve Number method are examples of very simple rainfall–runoff models that rely on one or a small number of parameters to represent complex watershed behavior. While these methods are somewhat antiquated given today's computational efficiency, they provide a clear and accessible way to see how model structure and parameter choices affect runoff estimates. Through these models, we will focus less on precise prediction and more on understanding how assumptions and parameterization shape our representation of hydrologic systems.

The **Rational Method** is a type of simple hydrological analysis used to estimate the *peak runoff rate* from a small watershed during a rainfall event. It is particularly useful for estimating the amount of water that will flow through a particular area during a storm, like a drainage system or culvert. Despite the existence of more advanced methods, this approach remains widely used in practice for its simplicity and ability to provide quick approximations, making it invaluable for preliminary assessments and as a foundation for understanding more complex hydrological and environmental modeling techniques.

Here is a 5-minute video to get started: 

```{r, echo=FALSE}
knitr::include_url("https://www.youtube.com/embed/brNpLh21UCg")
```

#### Reading - Rational Method.<br> 
Read at least sections 2 and 3 to for the formula and an example <br> 

- [The Rational Method](https://www.waternz.org.nz/Attachment?Action=Download&Attachment_id=846){target="_blank"}

Some helpful terminology:

<u>runoff coefficient</u> - represents how much rainfall actually becomes runoff<br>
<u>time of concentration</u> - the time it takes for some mass of precipitation to travel from the most remote point in a watershed to the outlet or point of interest. e.g., how long it takes a drop of rain to reach a culvert after it falls to the ground. 

#### Background information - Curve Number

The NRCS (Natural Resources Conservation Science) **curve number** (CN) is a parameter used to estimate the *total runoff volume* of water that will run off an ungaged watershed during a storm event. You may also see 'SCS CN' in texts. NRCS was previously known as Soil Conservation Science, they are the same. The curve number is based on soil type, land use and antecedent moisture conditions. So it is a parameter that summarizes multiple characteristics into one value. It was designed as a simple tool to describe typical watershed response from infrequent rainfall anywhere in the US for watersheds with the same soil type, land use, and surface runoff conditions. The CN method is a single event model to estimate of runoff volume from rainfall events (not peak discharge or a hydrograph). 

To understand the function and derivation of the CN number, let's start with the <br>
the NRCS runoff equation:

$$
Q = \frac{{(P - I_{a})^2}}{{P - I_{a} + S}}
$$
Where Q = runoff(in) <br>
P = rainfall (in) <br>
S = potential maximum retention after runoff begins
I<sub>a</sub> = initial abstraction (initial amount of rainfall that is intercepted by the watershed surface and does not immediately contribute to runoff)

I<sub>a</sub> is assumed to reduce to 0.2S based on empirical observations by NRCS. If:
$$
S = \frac{{1000}}{{CN}} - 10
$$
the runoff equation therefore reduces to:
$$
Q = \frac{{[P - 0.02\left(\frac{{1000}}{{CN}} - 10\right)]^2}}{{P + 0.8\left(\frac{{1000}}{{CN}} - 10\right)}}
$$

#### Reading - Curve numbers<br> 

Curve Number selection tables are available from the
[US Army Corps.](https://www.hec.usace.army.mil/confluence/hmsdocs/hmstrm/cn-tables){target="_blank"}

Slides on selecting curve number start around slide 8. <br>
- [Link](https://cdn.serc.carleton.edu/files/geoinformatics/steps/presentation_selecting_cn_vari.pdf){target="_blank"}

#### Reading - Supporting material

Time of concentration. Up to "other considerations", pages 15-1 to 15-9. <br>
- [Link](https://irrigationtoolbox.com/NEH/Part630_Hydrology/NEH630-ch15draft.pdf){target="_blank"}

We will use the Kirpich method to calculate the time of concentration. Here is the citation for your reference.

Kirpich, Z.P. (1940). "Time of concentration of small agricultural watersheds". Civil Engineering. 10 (6): 362.

### Repo link
The repo for this module can be found [here](https://github.com/tpcovino/03_rational_and_CN_methods.git){target="_blank"}

You will also need this link to select a parameter value 'C' or the runoff coefficient for the script (~line 117):
Look at this [table](https://www.dropbox.com/scl/fi/tkofgmpnroug8wwe8x16z/Rational.Method.C.png?rlkey=qgcyayk10j94is3hwjfxuzwz5&dl=0) to select C.
